In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv(r'F:\Data_science_projects\Recommendation_sytem\Movielens\datasets/clean_data.csv')

In [3]:
data.head(2)

userId  movieId  rating           title                      genres  \
0       1        2     3.5  Jumanji (1995)  Adventure|Children|Fantasy   
1       5        2     3.0  Jumanji (1995)  Adventure|Children|Fantasy   

   TotalRatingCount  
0               112  
1               112

In [4]:
data['title']

0                   Jumanji (1995)
1                   Jumanji (1995)
2                   Jumanji (1995)
3                   Jumanji (1995)
4                   Jumanji (1995)
                   ...            
99995    He Walked by Night (1948)
99996      Lone Ranger, The (1956)
99997      Gardens of Stone (1987)
99998            Field, The (1990)
99999              Fired Up (2009)
Name: title, Length: 100000, dtype: object

In [6]:
len(set(data['title']))

8225

In [7]:
data.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres', 'TotalRatingCount'], dtype='object')

In [9]:

pivot_table=data.pivot_table(index='title',columns='userId',values='rating').fillna(0)

In [10]:
pivot_table

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  2.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                   0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                0.0  0.0  0.0  ...  0.0  0.0  0.0   
'burbs, The (1989)                       0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                      ...  ...  ...  ...  ...  ...  ...   
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  ...  0.0  0.0  0.0   
eXistenZ (1999)                          0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx (2002)                               0.0  0.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)           0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                    0.0  0.0  0.0  ...  0.0  4.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Neath the Arizona Skies (1934)          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'burbs, The (1989)                       0.0  0.0  0.0  0.0  3.5  0.0  0.0  
...                                      ...  ...  ...  ...  ...  ...  ...  
\\"Great Performances\"\" Cats (1998)"   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
eXistenZ (1999)                          0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx (2002)                               0.0  0.0  0.0  0.0  0.0  0.0  0.0  
xXx: State of the Union (2005)           0.0  0.0  0.0  0.0  0.0  0.0  0.0  
¡Three Amigos! (1986)                    3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[8225 rows x 702 columns]

In [11]:
pivot_table.shape

#its shape will be (unique Title * unique User ID)

(8225, 702)

In [12]:
from scipy.sparse import csr_matrix

In [13]:
# Convert the pivot_table into an array matrix
pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
features_matrix=csr_matrix(pivot_table.values)

In [15]:
features_matrix

<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

In [16]:
from sklearn.neighbors import NearestNeighbors

In [17]:
model=NearestNeighbors(metric='cosine',algorithm='brute')

In [18]:
model.fit(features_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [20]:
pivot_table.shape[0]

8225

In [23]:
#picking up one random record/row
query_index=np.random.choice(pivot_table.shape[0])

In [24]:
query_index

4209

In [30]:
pivot_table.shape[1]

702

In [27]:
#picking up one random column
query_ind=np.random.choice(pivot_table.shape[1])

In [28]:
query_ind

533

In [37]:
pivot_table.iloc[4209,:]

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
698    0.0
699    0.0
700    0.0
701    0.0
702    0.0
Name: Last Temptation of Christ, The (1988), Length: 702, dtype: float64

In [42]:
pivot_table.iloc[4209,:].values.reshape(1,-1)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 2. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. 

In [43]:
#to check similar movie for 4209 where 4209 is a movie_ID
#values.reshape(1, -1),to get in the form of series

distances,indices=model.kneighbors(pivot_table.iloc[query_index,:].values.reshape(1,-1),n_neighbors=8)

In [44]:
distances

array([[0.        , 0.42469558, 0.47014058, 0.47615116, 0.49020388,
        0.49020388, 0.50598491, 0.50847912]])

#### lets try to make results more user-friendly...

In [46]:
indices.flatten()

array([4209, 1829, 5108, 2978, 2751, 1074, 7706, 1990], dtype=int64)

In [47]:
pivot_table.index[4209]

'Last Temptation of Christ, The (1988)'

In [49]:
pivot_table.iloc[indices.flatten()].index

Index(['Last Temptation of Christ, The (1988)', 'Dangerous Liaisons (1988)',
       'My Man Godfrey (1957)', 'Go Fish (1994)', 'Frankie Starlight (1995)',
       'Bound for Glory (1976)', 'Up at the Villa (2000)',
       'Desert Bloom (1986)'],
      dtype='object', name='title')

In [54]:
pivot_table.index[indices.flatten()][3]

'Go Fish (1994)'

In [50]:
distances.flatten()

array([0.        , 0.42469558, 0.47014058, 0.47615116, 0.49020388,
       0.49020388, 0.50598491, 0.50847912])

In [55]:
for i in range(0,len(distances.flatten())):
    if i==0:
        print('Recommendations for {0}'.format(pivot_table.index[query_index]))
    
    else:
        print('{} : {} , with a distance of {}'.format(i,pivot_table.index[indices.flatten()[i]],distances.flatten()[i]))

Recommendations for Last Temptation of Christ, The (1988)
1 : Dangerous Liaisons (1988) , with a distance of 0.42469557924062284
2 : My Man Godfrey (1957) , with a distance of 0.4701405762384343
3 : Go Fish (1994) , with a distance of 0.4761511584720963
4 : Frankie Starlight (1995) , with a distance of 0.49020387768154294
5 : Bound for Glory (1976) , with a distance of 0.49020387768154294
6 : Up at the Villa (2000) , with a distance of 0.5059849059839756
7 : Desert Bloom (1986) , with a distance of 0.5084791232370767
